app/application/main/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, StringField, IntegerField

class HomeForm(FlaskForm):
    search_term=StringField('Search for')
    radius = IntegerField('Radius (km)', default=200)
    location_field = StringField('Location (lat/lon)', default="43.65189362, -79.38171387")
    search_button=SubmitField('Search')

app/application/__init__.py
from flask import Flask

import logging
from logging.handlers import RotatingFileHandler
import os

from config import Config



def create_app(config_class=Config):
    app = Flask(__name__, instance_relative_config=False)
    app.config.from_object(config_class)
    with app.app_context():

        from application.errors import errors_bp
        app.register_blueprint(errors_bp)

        from application.main import main_bp
        app.register_blueprint(main_bp)

        if not app.debug:
            if not os.path.exists('logs'):
                os.mkdir('logs')
            file_handler = RotatingFileHandler('logs/access.log', maxBytes=10240,
                                               backupCount=10)
            file_handler.setFormatter(logging.Formatter(
                '%(asctime)s %(levelname)s: %(message)s [in %(pathname)s:%(lineno)d]'))
            file_handler.setLevel(logging.INFO)
            app.logger.addHandler(file_handler)

            app.logger.setLevel(logging.INFO)
            app.logger.info('Startup')
    
        return app

app/application/main/__init__.py
from flask import Blueprint

main_bp = Blueprint('main', __name__
                    , template_folder='templates'
                    , static_folder='static'
                    , static_url_path='/assets'
                )

from application.main import routes

app/application/main/routes.py
from flask import (
    render_template, current_app
)
import requests
import re
from datetime import datetime

import pytz

from application.main import main_bp
from application.main.forms import HomeForm




@main_bp.route('/', methods=['GET', 'POST'])
def index():
    form = HomeForm()
    auction_items = list()
    ms_url="https://maxsold.api.maxsold.com/algolia/search"
    ms_api_key="c4e2c29964993277b9d90061957cff81"
    ms_origin="https://maxsold.com"
    ms_body= {
    
    "selectedFilters": {
        "coordinates": {
            "lat": 43.65189362,
            "lng": -79.38171387
        },
        "distance": 200,
        "searchText": "",
        "address": "Britt, ON, Canada",
        "urlComponents": {
            "country": "canada",
            "state": "ontario",
            "region": "toronto",
            "auctionType": "",
            "category": "",
            "subCategory": []
        }
    },
    "algoliaIndexName": "hpitem",
    "hitsPerPage": 1000,
    "page": 0

    }
    ms_headers = {
        "x-api-key": ms_api_key,
        "Origin": ms_origin
    }



    if form.validate_on_submit():
        ms_body['selectedFilters']['searchText'] = form.search_term.data
        if form.radius.data > 0:
            ms_body['selectedFilters']['distance'] = form.radius.data * 1
        if form.location_field.data:
            ms_body['selectedFilters']['coordinates']['lat'] = float(form.location_field.data.split(',')[0])
            ms_body['selectedFilters']['coordinates']['lng'] = float(form.location_field.data.split(',')[1])
        r = requests.post(url=ms_url, headers=ms_headers, json=ms_body)
        response = r.json()
        
        auction_items = sorted(response['hits'], key=lambda d: d['end_date'])
        today = datetime.now().astimezone(pytz.timezone(current_app.config['TZ_LOCAL']))
        for item in auction_items:
            title = re.sub(r'[^A-Za-z ]+', '', item['title']).split()
            title.append(item['objectID'])
            item['item_link'] = '-'.join(title)
            end_date = datetime.fromtimestamp(item['end_date']).astimezone(pytz.timezone(current_app.config['TZ_LOCAL']))
            item['end_date'] = end_date
            item['ends_today'] = True if end_date.date() == today.date() else False



    return render_template(
        'index.html',
        title = 'Maxsold search',
        auction_items=auction_items,
        form = form
    )

app/application/templates/base.html
<!doctype html>
<html lang="en">

    <head>
        <meta name="charset" content="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        
        <title>{{ title }}</title>

        <link rel="shortcut icon" type="image/jpg" href="{{ url_for('static', filename='favicon.ico') }}"/>

        {% block styles %}
        <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
        {% endblock %}
        
        {% block scripts_head %}
        <script src="{{ url_for('static', filename='js/jquery-3.5.1.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}" ></script>
        <script src="{{ url_for('static', filename='js/main.js') }}" ></script>
        {% endblock %}
    </head>

    {% import 'macros/nav.html' as nav %}

    <body>
        {{ nav.render_main_nav() }}

        <div class="container-fluid mt-4 mb-5">
        {% block content %}
        {% endblock %}
        </div>

        {% block scripts %}{% endblock %}

    </body>
</html>

app/application/templates/macros/nav.html
{% macro render_main_nav() %}
<header class="px-md-4 mb-3 bg-danger border-bottom border-dark shadow-sm">
  <div class="container-fluid navbar p-0 d-flex flex-column flex-md-row align-items-center">
    <a href="{{ url_for('main.index') }}" class="text-light navbar-brand me-0 d-flex align-items-center">
     Maxsold Search 
    </a>
  </div>
</header>
{% endmacro %}